### ISSUE TITLE
ASAN reports a bug in lex.c when running the "expand" unittest

### ISSUE THREAD

**Issue by krader1961** [att/ast#685]
```
==20797==ERROR: AddressSanitizer: global-buffer-overflow on address 0x000108e7e4bf at pc 0x000108afe918 bp 0x7fff5725dbc0 sp 0x7fff5725dbb8
READ of size 1 at 0x000108e7e4bf thread T0
    #0 0x108afe917 in sh_lex lex.c:1159
    #1 0x108bc53ae in simple parse.c:1430
    #2 0x108bbd0db in item parse.c:1278
    #3 0x108bb9e15 in term parse.c:560
...
0x000108e7e4bf is located 1 bytes to the left of global variable 'sh_lexstate2' defined in '../src/cmd/ksh93/data/lexstates.c:92:19' (0x108e7e4c0) of size 256
0x000108e7e4bf is located 63 bytes to the right of global variable 'sh_lexstate1' defined in '../src/cmd/ksh93/data/lexstates.c:61:19' (0x108e7e380) of size 256
```

The problem is this block of code in *src/cmd/ksh93/sh/lex.c*:

```
                if (sh_isoption(lp->sh, SH_BRACEEXPAND) && c == LBRACE && !assignment &&
                    state[n] != S_BREAK && !lp->lex.incase && !lp->lex.intest &&
                    !lp->lex.skipword) {
                    wordflags |= ARG_EXP;
                }
```

The error is that `n` is -1 and thus `state[n]` is indexing the entry prior to the array pointed to by `state`. FWIW, `state` is an alias for array `sh_lexstate2` at that juncture.

**Comment by krader1961** [comment]
What's interesting is the preceding block of code explicitly tests if `n` is not negative but only breaks out of the loop, thus avoiding the invalid dereference, if `lp->lex.reservok` is true:

```
                if (n > 0) {
                    fcseek(-LEN);
                } else if (lp->lex.reservok) {
                    break;
                }
```

**Comment by krader1961** [comment]
The block of code in my previous comment makes no sense AFAICT. If `fcgetc()` returns -1 which means no character was available (EOF?) then in what universe does it make sense to do anything else than break out of the loop? Why would that be predicated on `lp->lex.reservok`? We didn't find another character so any of the subsequent tests of that character are meaningless.
